version: '3.3'
services:
  pms-docker:
    container_name: plex
    ports:
      - '32400:32400/tcp'
      - '3005:3005/tcp'
      - '8324:8324/tcp'
      - '32469:32469/tcp'
      - '1900:1900/udp'
      - '32410:32410/udp'
      - '32412:32412/udp'
      - '32413:32413/udp'
      - '32414:32414/udp'
    environment:
      - TZ=America/Chicago
      - PLEX_CLAIM=<claim token>
      - 'ADVERTISE_IP=http://<ip address>:32400/'
    volumes:
      - '/tank/Plex/plex-data/config:/config'
      - '/tank/Plex/plex-data/transcode:/transcode'
      - '/tank/Plex:/data'
    image: 'plexinc/pms-docker:plexpass'